### ISSUE TITLE
Hangs after a certain period of time

### ISSUE THREAD

**Issue by johnsushant** [scrapinghub/wappalyzer-python#5]
On a 4GB memory machine, if I keep giving wappalyzer input to analyse, it will hang after reaching about 2.6GB of memory and stay stuck. I tried pre-scraping sites using scrapy and then giving it as input to the analyse_from_data function but this hangs in the exact same way.

**Comment by redapple** [comment]
Hello @johnsushant , thanks for you feedback.
Unfortunately, wappalyzer-python is not maintained anymore and no one at Scrapinghub is currently working on it.
Ownership transfer requests are welcome.
